import { Payment,columns } from "./columns";
import { DataTable } from "./data-table";

const getData = async (): Promise<Payment[]> => {
  return [
    {
      id: "728ed521",
      amount: 1340000,
      status: "pending",
      fullName: "John Doe",
      userId: "45",
      email: "johndoe@gmail.com",
    },
    {
      id: "728ed522",
      amount: 1240000,
      status: "success",
      fullName: "Jane Doe",
      userId: "78",
      email: "janedoe@gmail.com",
    },
    {
      id: "728ed523",
      amount: 1670000,
      status: "success",
      fullName: "Mike Galloway",
      userId: "23",
      email: "mikegalloway@gmail.com",
    },
    {
      id: "728ed524",
      amount: 1560000,
      status: "failed",
      fullName: "Minerva Robinson",
      userId: "91",
      email: "minerbarobinson@gmail.com",
    },
    {
      id: "728ed525",
      amount: 1450000,
      status: "success",
      fullName: "Mable Clayton",
      userId: "12",
      email: "mableclayton@gmail.com",
    },
    {
      id: "728ed526",
      amount: 1890000,
      status: "pending",
      fullName: "Nathan McDaniel",
      userId: "67",
      email: "nathanmcdaniel@gmail.com",
    },
    {
      id: "728ed527",
      amount: 1780000,
      status: "success",
      fullName: "Myrtie Lamb",
      userId: "34",
      email: "myrtielamb@gmail.com",
    },
    {
      id: "728ed528",
      amount: 1900000,
      status: "success",
      fullName: "Leona Bryant",
      userId: "56",
      email: "leonabryant@gmail.com",
    },
    {
      id: "728ed529",
      amount: 1340000,
      status: "failed",
      fullName: "Aaron Willis",
      userId: "89",
      email: "aaronwillis@gmail.com",
    },
    {
      id: "728ed52a",
      amount: 5430000,
      status: "success",
      fullName: "Joel Keller",
      userId: "5",
      email: "joelkeller@gmail.com",
    },
    {
      id: "728ed52b",
      amount: 2340000,
      status: "pending",
      fullName: "Daniel Ellis",
      userId: "72",
      email: "danielellis@gmail.com",
    },
    {
      id: "728ed52c",
      amount: 3450000,
      status: "success",
      fullName: "Gordon Kennedy",
      userId: "41",
      email: "gordonkennedy@gmail.com",
    },
    {
      id: "728ed52d",
      amount: 335,
      status: "failed",
      fullName: "Emily Hoffman",
      userId: "98",
      email: "emilyhoffman@gmail.com",
    },
    {
      id: "728ed52e",
      amount: 6640000,
      status: "pending",
      fullName: "Jeffery Garrett",
      userId: "16",
      email: "jefferygarrett@gmail.com",
    },
    {
      id: "728ed52f",
      amount: 3320000,
      status: "success",
      fullName: "Ralph Baker",
      userId: "63",
      email: "ralphbaker@gmail.com",
    },
    {
      id: "728ed52g",
      amount: 4130000,
      status: "failed",
      fullName: "Seth Fields",
      userId: "27",
      email: "sethfields@gmail.com",
    },
    {
      id: "728ed52h",
      amount: 3450000,
      status: "pending",
      fullName: "Julia Webb",
      userId: "84",
      email: "juliawebb@gmail.com",
    },
    {
      id: "728ed52i",
      amount: 7540000,
      status: "success",
      fullName: "Gary Banks",
      userId: "39",
      email: "garybanks@gmail.com",
    },
    {
      id: "728ed52j",
      amount: 6430000,
      status: "failed",
      fullName: "Flora Chambers",
      userId: "55",
      email: "florachambers@gmail.com",
    },
    {
      id: "728ed52k",
      amount: 543,
      status: "pending",
      fullName: "Steve Hanson",
      userId: "8",
      email: "stevehanson@gmail.com",
    },
    {
      id: "728ed52l",
      amount: 324,
      status: "success",
      fullName: "Lola Robinson",
      userId: "76",
      email: "lolarobinson@gmail.com",
    },
    {
      id: "728ed52m",
      amount: 123,
      status: "pending",
      fullName: "Ethel Waters",
      userId: "31",
      email: "ethelwaters@gmail.com",
    },
    {
      id: "728ed52n",
      amount: 422,
      status: "failed",
      fullName: "Grace Edwards",
      userId: "94",
      email: "graceedwards@gmail.com",
    },
    {
      id: "728ed52o",
      amount: 712,
      status: "success",
      fullName: "Sallie Wong",
      userId: "19",
      email: "salliewong@gmail.com",
    },
    {
      id: "728ed52p",
      amount: 360,
      status: "success",
      fullName: "Bryan Gutierrez",
      userId: "62",
      email: "bryangutierrez@gmail.com",
    },
    {
      id: "728ed52q",
      amount: 454,
      status: "pending",
      fullName: "Erik Rice",
      userId: "47",
      email: "erikrice@gmail.com",
    },
    {
      id: "728ed52r",
      amount: 382,
      status: "success",
      fullName: "Jordan Atkins",
      userId: "81",
      email: "jordanatkins@gmail.com",
    },
    {
      id: "728ed52s",
      amount: 328,
      status: "failed",
      fullName: "Bill Brewer",
      userId: "3",
      email: "billbrewer@gmail.com",
    },
    {
      id: "728ed52t",
      amount: 250,
      status: "success",
      fullName: "Edwin Morris",
      userId: "68",
      email: "edwinmorris@gmail.com",
    },
    {
      id: "728ed52u",
      amount: 658,
      status: "success",
      fullName: "Harold Becker",
      userId: "25",
      email: "haroldbecker@gmail.com",
    },
    {
      id: "728ed52v",
      amount: 691,
      status: "success",
      fullName: "Hannah Rodriguez",
      userId: "92",
      email: "hannahrodriguez@gmail.com",
    },
    {
      id: "728ed52w",
      amount: 969,
      status: "success",
      fullName: "Zachary Beck",
      userId: "14",
      email: "zacharybeck@gmail.com",
    },
    {
      id: "728ed52x",
      amount: 617,
      status: "failed",
      fullName: "Frances Potter",
      userId: "59",
      email: "francespotter@gmail.com",
    },
    {
      id: "728ed52y",
      amount: 173,
      status: "success",
      fullName: "Raymond Murray",
      userId: "36",
      email: "raymondmurray@gmail.com",
    },
    {
      id: "728ed52z",
      amount: 843,
      status: "success",
      fullName: "Adam Sherman",
      userId: "74",
      email: "adamsherman@gmail.com",
    },
    {
      id: "728ed521f",
      amount: 914,
      status: "pending",
      fullName: "Anne Cruz",
      userId: "50",
      email: "annecruz@gmail.com",
    },
  ];
};

const PaymentsPage = async () => {
  const data = await getData();
  return (
    <div className="">
      <div className="mb-8 px-4 py-2 bg-secondary rounded-md">
        <h1 className="font-semibold">Tất cả thanh toán</h1>
      </div>
      <DataTable columns={columns} data={data}/>
    </div>
  );
};

export default PaymentsPage;
